apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tickets
resources:
- namespace.yaml
- catalog.yaml
- inventory.yaml
- orders.yaml
- payments.yaml
- gateway.yaml
- workers.yaml
- simulator.yaml
- seeder.yaml
- web.yaml
images:
- name: ghcr.io/slash3b/tickets-catalog
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-gateway
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-inventory
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-orders
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-payments
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-seeder
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-simulator
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-web
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
- name: ghcr.io/slash3b/tickets-workers
  newTag: 3333faf58e20b4ef9c7e9fd82b604455004839fc
