apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tickets
resources:
- namespace.yaml
- gateway.yaml
- workers.yaml
- simulator.yaml
- seeder.yaml
- web.yaml
images:
- name: ghcr.io/slash3b/tickets-gateway
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
- name: ghcr.io/slash3b/tickets-seeder
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
- name: ghcr.io/slash3b/tickets-simulator
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
- name: ghcr.io/slash3b/tickets-web
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
- name: ghcr.io/slash3b/tickets-workers
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
