apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tickets
resources:
- namespace.yaml
- catalog.yaml
- inventory.yaml
- orders.yaml
- payments.yaml
- gateway.yaml
- workers.yaml
- simulator.yaml
- seeder.yaml
- web.yaml
- vpa.yaml
- hpa.yaml
images:
- name: ghcr.io/slash3b/tickets-catalog
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-gateway
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-inventory
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-orders
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-payments
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-seeder
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-simulator
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-web
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
- name: ghcr.io/slash3b/tickets-workers
  newTag: 474e0ff96142eb075c9f8087578884cd7b9e948d
