apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bank
resources:
- namespace.yaml
- deployment.yaml
images:
- name: ghcr.io/slash3b/tickets-bank
  newTag: bf7970c53423e6892132d067769c94138b8ddba7
