apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bank
resources:
- namespace.yaml
- deployment.yaml
images:
- name: ghcr.io/slash3b/tickets-bank
  newTag: f4816b8ca5ab1b8b11b995531057cc1ce6aa028b
