apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bank
resources:
- namespace.yaml
- deployment.yaml
images:
- name: ghcr.io/slash3b/tickets-bank
  newTag: bb83898a1c0c2b206d9ae16b19b121d9de9a5307
